config/routes.rb
Rails.application.routes.draw do


  devise_for :usuarios
  root 'monitor_inspectores#index'
  resources :monitor_inspectores do 
    collection do 
      get 'carga_comunas'
      get 'carga_usuarios'
      get 'carga_sedes'
    end
  end

  # > Rutas Catastros
  # > Perfiles de Usuarios
  resources :perfiles do
    collection do
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
  match 'catastro/perfiles' => 'perfils#index', via: [:get, :post]

  # > Usuarios Administrativos
  resources :usuarios_administrativos do
    collection do
    	post 'cambiar'
      get 'modificar_contrasena'
      get 'exportar_pdf'
      get 'exportar_csv'
    end
  end
  match 'catastro/empleados/administrativos' => 'usuarios_administrativos#index', via: [:post, :get]

  # > Usuarios Agente de Terreno
  resources :usuarios_agentes_terreno do
    collection do
    	post 'cambiar'
      get 'modificar_contrasena'
      get 'exportar_pdf'
      get 'exportar_csv'
    end
  end
  match 'catastro/empleados/agentes_terreno' => 'usuarios_agentes_terreno#index', via: [:post, :get]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #user ||= Usuario.new # guest user (not logged in)
    #if user.perfil_id == 1? #Administrador
    #  can :manage, :all
    #else
    #  can :read, :all
    #end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comuna.rb
class Comuna < ApplicationRecord
  belongs_to :region
end

app/models/direccion.rb
class Direccion < ApplicationRecord
end

app/models/estadistica.rb
class Estadistica < ApplicationRecord
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/models/evento.rb
class Evento < ApplicationRecord
end

app/models/orden_trabajo.rb
class OrdenTrabajo < ApplicationRecord
  belongs_to :estado_punto_control
  belongs_to :tarea
  belongs_to :tipo_servivio
  belongs_to :punto_control
  belongs_to :comuna
  belongs_to :region
  belongs_to :turno
  belongs_to :sentido
  belongs_to :sede
  belongs_to :fecha_modificacion
end

app/models/perfil.rb
class Perfil < ApplicationRecord
end

app/models/punto_control.rb
class PuntoControl < ApplicationRecord
  belongs_to :estado_punto_contol
  belongs_to :comuna
  belongs_to :region
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/sede.rb
class Sede < ApplicationRecord
  belongs_to :region
  has_and_belongs_to_many :usuario
end

app/models/sedes_usuario.rb
class SedesUsuario < ApplicationRecord
  belongs_to :sede
  belongs_to :usuario
end

app/models/sentido.rb
class Sentido < ApplicationRecord
end

app/models/tarea.rb
class Tarea < ApplicationRecord
end

app/models/tareas_usuario.rb
class TareasUsuario < ApplicationRecord
  belongs_to :usuario
end

app/models/tipo_servicio.rb
class TipoServicio < ApplicationRecord
end

app/models/turno.rb
class Turno < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable


  belongs_to :perfil
  has_one :empleado
	validates :email, uniqueness: {message: "Nombre de usuario ya se encuentra registrado"}
  has_and_belongs_to_many :sede
end

app/models/usuario_mtt.rb
class UsuarioMtt < ApplicationRecord
  belongs_to :sede
  belongs_to :region
end

app/models/usuarios_tarea.rb
class UsuariosTarea < ApplicationRecord
  belongs_to :usuario
  belongs_to :sede
  belongs_to :region
end

app/views/layouts/_menu_administrador.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Bitácora</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span class="fas fa-map-marked-alt"></span>  Visualización de Eventos
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="fas fa-list-alt"></span> Mantenedores
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Usuarios</a>
          <a class="dropdown-item" href="#">Perfiles</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto" >
      <li class="nav-item dropdown float-left">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="fas fa-user"></span> <%= current_usuario.email%>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%=link_to 'Salir', destroy_usuario_session_path, method: :delete, :class => "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</nav>
<br>
<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <!-- Google Maps -->
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCMTSqaDJR9RFHg947hREJzmvcdkyrY9-4"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <!-- Iconos fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <%if usuario_signed_in? %>
  <!-- Dropdown Structure -->
    <%= render 'layouts/menu_administrador' %>

  <% else %>
    <%= render 'login' %>
    <style>
    div.main{
      background: #0264d6; /* Old browsers */
      background: -moz-radial-gradient(center, ellipse cover,  #0264d6 1%, #eb6501 100%); /* FF3.6+ */
      background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(1%,#0264d6), color-stop(100%,#eb6501)); /* Chrome,Safari4+ */
      background: -webkit-radial-gradient(center, ellipse cover,  #0264d6 1%,#eb6501 100%); /* Chrome10+,Safari5.1+ */
      background: -o-radial-gradient(center, ellipse cover,  #0264d6 1%,#eb6501 100%); /* Opera 12+ */
      background: -ms-radial-gradient(center, ellipse cover,  #0264d6 1%,#eb6501 100%); /* IE10+ */
      background: radial-gradient(ellipse at center, #ee8589 1%,#da393e 100%);
      filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#0264d6', endColorstr='#eb6501',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
      height:calc(100vh);
      width:100%;
      }

      [class*="fontawesome-"]:before {
        font-family: 'FontAwesome', sans-serif;
      }

      /* ---------- GENERAL ---------- */

      * {
        box-sizing: border-box;
          margin:0px auto;

        &:before,
        &:after {
          box-sizing: border-box;
        }

      }

      body {

        color: #606468;
        font: 87.5%/1.5em 'Open Sans', sans-serif;
        margin: 0;
      }

      a {
        color: #eee;
        text-decoration: none;
      }

      a:hover {
        text-decoration: underline;
      }

      input {
        border: none;
        font-family: 'Open Sans', Arial, sans-serif;
        font-size: 14px;
        line-height: 1.5em;
        padding: 0;
        -webkit-appearance: none;
      }

      p {
        line-height: 1.5em;
      }

      .clearfix {
        *zoom: 1;

        &:before,
        &:after {
          content: ' ';
          display: table;
        }

        &:after {
          clear: both;
        }

      }

      .container {
        left: 50%;
        position: fixed;
        top: 50%;
        transform: translate(-50%, -50%);
      }

      /* ---------- LOGIN ---------- */

      #login form{
        width: 250px;
      }
      #login, .logo{
          display:inline-block;
          width:40%;
      }
      #login{
      border-right:1px solid #fff;
        padding: 0px 22px;
        width: 59%;
      }
      .logo{
      color:#fff;
      font-size:50px;
        line-height: 125px;
      }

      #login form span.fa {
        background-color: #fff;
        border-radius: 3px 0px 0px 3px;
        color: #000;
        display: block;
        float: left;
        height: 50px;
          font-size:24px;
        line-height: 50px;
        text-align: center;
        width: 50px;
      }

      #login form input {
        height: 50px;
      }
      fieldset{
          padding:0;
          border:0;
          margin: 0;

      }
      #login form input[type="text"], input[type="password"] {
        background-color: #fff;
        border-radius: 0px 3px 3px 0px;
        color: #000;
        margin-bottom: 1em;
        padding: 0 16px;
        width: 200px;
      }

      #login form input[type="submit"] {
        border-radius: 3px;
        -moz-border-radius: 3px;
        -webkit-border-radius: 3px;
        background-color: #000000;
        color: #eee;
        font-weight: bold;
        /* margin-bottom: 2em; */
        text-transform: uppercase;
        padding: 5px 10px;
        height: 30px;
      }

      #login form input[type="submit"]:hover {
        background-color: #f4c800;
      }

      #login > p {
        text-align: center;
      }

      #login > p span {
        padding-left: 5px;
      }
      .middle {
        display: flex;
        width: 600px;
      }
     </style>
  <% end %>

app/views/layouts/pdf.html.erb
<!-- Navegación Superior -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="logo-empresa">
    <!-- <%= link_to (image_tag 'isotipo_fas.png',:width => 60, :height => 50), {controller: "bienvenida", action: "index"} %> -->
    <%= link_to (image_tag 'isotipo_fastbilling.png',:width => 60, :height => 50), {controller: "bienvenida", action: "index"} %>
    <%= link_to (image_tag 'logo_cge.png',:width => 50, :height => 50), {controller: "bienvenida", action: "index"} %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse mr-auto " id="navbarNavDropdown">
    
  </div>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mdi mdi-format-list-bulleted mdi-18px"></span> Catastros 
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%=link_to '<span class="mdi mdi-face-profile"></span> Perfiles de Usuario'.html_safe, catastro_perfiles_path, :class => "dropdown-item" %>
            <%=link_to '<span class="mdi mdi-account-multiple"></span> Usuarios Administrativos'.html_safe, catastro_empleados_administrativos_path, :class => "dropdown-item" %>
            <%=link_to '<span class="mdi mdi-account-multiple"></span> Usuarios Agentes de Terreno'.html_safe, catastro_empleados_agentes_terreno_path, :class => "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%=link_to '<span class="mdi mdi-file-tree"></span> Claves y Observaciones de Lectura'.html_safe, catastro_clave_lecturas_path, :class => "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%=link_to '<span class="mdi mdi-file-tree"></span> Observaciones de Reparto'.html_safe, catastro_observacion_repartos_path, :class => "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown active">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> <i class="mdi mdi-file-document mdi-18px"></i>Lecturas <b class="caret"></b></a>
          <ul class="dropdown-menu multi-level">
            <li class="dropdown-item dropdown-submenu">
              <a class="dropdown-toggle" data-toggle="dropdown"><span class="mdi mdi-worker"></span>  Operaciones</a>
              <ul class="dropdown-menu">
                <li><%=link_to '<span class="mdi mdi-file-import"></span> Importar Ordenes de lectura'.html_safe,lectura_operaciones_importar_ordenes_lectura_path,:class => "dropdown-item" %></li>
                <div class="dropdown-divider"></div>
                <li><%=link_to '<span class="mdi mdi-library-plus"></span> Asignación de Libreta de O.L'.html_safe, lectura_operaciones_asignacion_lecturas_path,:class => "dropdown-item" %></li>
                <li><%=link_to '<span class="mdi mdi-printer"></span> Impresión de Libreta de O.L'.html_safe, lectura_operaciones_impresion_ruteros_path,:class => "dropdown-item"%></li>
                <div class="dropdown-divider"></div>
                <li><%=link_to '<span class="mdi mdi-google-maps"></span> Monitoreo de Lectores en Terreno'.html_safe, lectura_operaciones_monitor_lectores_path,:class => "dropdown-item"%></li>
                <li><%=link_to '<span class="mdi mdi-minus-circle"></span> Cerrar Procesos'.html_safe, lectura_operaciones_cerrar_procesos_lecturas_path,:class => "dropdown-item"%></li>
              </ul>
              
            </li>

            <li class="dropdown-item dropdown-submenu">
              <a class="dropdown-toggle" data-toggle="dropdown"><span class="mdi mdi-chart-pie"></span>  Análisis en Línea</a>
              <ul class="dropdown-menu">
                <li><%=link_to '<span class="mdi mdi-file-plus"></span> Lectura Dictada Por Cliente'.html_safe,lectura_analisis_online_lectura_dictada_cliente_path,:class => "dropdown-item"%></li>
                <div class="dropdown-divider"></div>
                <li><%=link_to '<span class="mdi mdi-chart-bar-stacked"></span> Clientes Dudosos Máximos Y Mínimos'.html_safe, lectura_analisis_online_clientes_dudosos_path,:class => "dropdown-item"%></li>
                <li><%=link_to '<span class="mdi mdi-chart-bar-stacked"></span> Clientes Dudosos Improcedentes'.html_safe, lectura_analisis_online_clientes_improcedentes_path,:class => "dropdown-item"%></li>
                <div class="dropdown-divider"></div>
                <li><%=link_to '<span class="mdi mdi-file-multiple"></span> Histórico de Lecturas de un Cliente'.html_safe, lectura_analisis_online_historico_lecturas_path,:class => "dropdown-item"%></li>
                <li><%=link_to '<span class="mdi mdi-arrow-left"></span> Clientes Pendientes de Verificación'.html_safe,lectura_analisis_online_clientes_pendientes_verificacion_path,:class => "dropdown-item"%></li>
              </ul>
            </li>

            <li class="dropdown-item dropdown-submenu">
              <a class="dropdown-toggle" data-toggle="dropdown"><span class="mdi mdi-file-chart"></span> Reportes</a>
              <ul class="dropdown-menu">
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Efectividad de Procesos'.html_safe,lectura_reportes_efectividad_procesos_path,:class => "dropdown-item"%></li>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Efectividad por Porción'.html_safe,lectura_reportes_efectividad_porcion_path,:class => "dropdown-item"%></li>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span>Efectividad por Lector'.html_safe,lectura_reportes_efectividad_lector_path,:class => "dropdown-item"%></li>
                  <div class="dropdown-divider"></div>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Control de Folios Casa Cerrada'.html_safe,lectura_reportes_casa_cerrada_path,:class => "dropdown-item"%></li>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Control de Coordenadas GPS'.html_safe,lectura_reportes_control_coordenadas_gps_path,:class => "dropdown-item"%></li>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Control de Horas por Lector'.html_safe,lectura_reportes_control_horas_lector_terreno_path,:class => "dropdown-item"%></li>

                  <div class="dropdown-divider"></div>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Números de Intentos de Ingreso de Lectura'.html_safe,lectura_reportes_numero_intentos_lector_path,:class => "dropdown-item"%></li>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Tipo de Claves de Lectura'.html_safe,lectura_reportes_tipos_claves_path,:class => "dropdown-item"%></li>
                  <div class="dropdown-divider"></div>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Llenado de Estanques'.html_safe,lectura_reportes_llenado_estanques_path,:class => "dropdown-item"%></li>
                  <li><%=link_to '<span class="mdi mdi-file-chart"></span> Clientes con "N" Veces sin Lectura Efectiva'.html_safe,reporte_nveces_sinlecturaefectiva_index_path,:class => "dropdown-item"%></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown active">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> <i class="mdi mdi-file-document mdi-18px"></i>Repartos <b class="caret"></b></a>
          <ul class="dropdown-menu multi-level">
            <li class="dropdown-item dropdown-submenu">
              <a class="dropdown-toggle" data-toggle="dropdown"><span class="mdi mdi-worker" style="color:#FE7F2D"></span>  Operaciones</a>
              <ul class="dropdown-menu">
                  <li><%=link_to 'Importar Ordenes de Reparto', reparto_operaciones_importar_ordenes_reparto_path,:class => "dropdown-item"%></li>
                  <li class="dropdown-divider"></li>
                  <li><%=link_to 'Asignación de Libreta O.R', reparto_operaciones_asignacion_repartos_path,:class => "dropdown-item"%></li>
                  <li class="dropdown-divider"></li>
                  <li><%=link_to 'Monitoreo de Agentes en Terreno', reparto_operaciones_monitor_repartidores_path,:class => "dropdown-item"%></li>
                  <li class="dropdown-divider"></li>
                  <li><%=link_to 'Cerrar Procesos', reparto_operaciones_cerrar_procesos_repartos_path,:class => "dropdown-item"%></li>
              </ul>
            </li>

            <li class="dropdown-item dropdown-submenu">
              <a class="dropdown-toggle" data-toggle="dropdown"><span class="mdi mdi-chart-pie" style="color:#A1C181"></span>  Gestión Repartos</a>
              <ul class="dropdown-menu">
                  <li><%=link_to 'Historico Doc. de un Cliente', reparto_gestion_repartos_historico_documentos_path,:class => "dropdown-item"%></li>
                  <li><%=link_to 'Devolución de Documentos', reparto_gestion_repartos_devoluciones_path,:class => "dropdown-item"%></li>
              </ul>
            </li>

            <div class="dropdown-item dropdown-submenu">
              <a class="dropdown-toggle" data-toggle="dropdown"><span class="mdi mdi-file-chart" style="color:#233D4D"></span> Reportes</a>
              <ul class="dropdown-menu">
							  <li><%=link_to 'Efectividad de Procesos', reparto_reportes_efectividad_procesos_path,:class => "dropdown-item"%></li>
							  <div class="dropdown-divider"></div>
							  <li><%=link_to 'Devoluciones', reparto_reportes_devoluciones_path,:class => "dropdown-item"%></li>
							  <div class="dropdown-divider"></div>
							  <li><%=link_to 'Control Entregas', reparto_reportes_control_entregas_path,:class => "dropdown-item"%></li>
              </ul>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to '<i class="mdi mdi-cash-usd mdi-18px"></i> Facturación'.html_safe, { :action => "catastros", :controller => :menus}, :class => "nav-link"%> 
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mdi mdi-database mdi-18px"></span> Inventarios 
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%=link_to 'Empleados', empleados_path, :class => "dropdown-item" %>
              <%=link_to 'Equipos', empleados_path, :class => "dropdown-item" %>
              <%=link_to 'Marcas', empleados_path, :class => "dropdown-item" %>
              <%=link_to 'Modelos', empleados_path, :class => "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mdi mdi-help-circle mdi-18px"></span>  Manuales 
              </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                
            </div>
          </li>
    </ul>
    <ul class="navbar-nav ml-auto" >
      
      <li class="nav-item dropdown float-left">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_usuario.email%> <span class="mdi mdi-account-circle mdi-18px"></span>
          </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%=link_to 'Cerrar Sesión', destroy_usuario_session_path, method: :delete, :class => "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</nav>
<br>